import 'package:flutter/material.dart';
Color gren=Color(0xFF80E2D2);
Color backgroundgren=Color(0xff80E1D1);
Color white=Colors.white;
Color bcolor=Color(0xFF80E1D1);
Color btcolor=Colors.white;
Color tBorder1=Colors.white;
Color tBorder2=Color(0xFF80E1D1);
Color tHint1=Colors.white;
Color tHint2=Color(0xFF80E1D1);
Color circlecolor=Color(0xFF80E1D1);
///////////////////////////////////
String str_login="Login";
String str_register="Register";
String str_name="Name";
String str_email="Email";
String str_password='Password';
String str_passwordconfirm='Confirm password';
String str_companyname='Companys name';
String str_forgetpassword='Forget your password ?';
String str_code='code';
String str_send='Send';
String str_forogtparagraph1="Enter your registred email bellow ";
String str_forogtparagraph2="to recieve the password code ";
String str_resetpassword='Reset Password';
String str_productid='Id';
String str_productname='product';
String str_content ='quantity';
String str_price='price';
String str_add='Add';
String str_scan='Scan';
//////////////////////////////////////
String url_image_profile="assets/images/acc.png";
String url_image_logo='assets/images/logo.png';
String url_image_mail="assets/images/email.png";
String url_image_lock="assets/images/lock.png";